In [18]:
import numpy as np
from scipy import sparse
from scipy.sparse import csr_array
import pandas as pd

In [2]:
cd = np.load('/oak/stanford/groups/ljerby/SharedResources/Akana2024/Data/A375_cd.npy')
cd
# the large .npy file has been deleted manually

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
cd = csr_array(cd)
print(cd)
sparse.save_npz('/oak/stanford/groups/ljerby/SharedResources/Akana2024/Data/A375_cd',cd)
# sparse format can be more efficient and compact for perturb-seq data
# read the data with:
# cd = sparse.load_npz('path_to_your_file')
# convert to numpy:
# cd = cd.toarray()

  (0, 1011)	1.0
  (0, 1649)	1.0
  (3, 684)	1.0
  (3, 3503)	1.0
  (3, 4658)	1.0
  (3, 4712)	1.0
  (3, 4783)	1.0
  (6, 50)	1.0
  (6, 314)	1.0
  (6, 550)	1.0
  (6, 985)	1.0
  (6, 1072)	1.0
  (6, 1268)	1.0
  (6, 1697)	1.0
  (6, 2511)	1.0
  (6, 3279)	1.0
  (6, 3587)	1.0
  (6, 3604)	1.0
  (6, 3835)	1.0
  (6, 3880)	1.0
  (6, 3910)	1.0
  (6, 3924)	1.0
  (6, 4225)	1.0
  (6, 4246)	1.0
  (6, 4352)	1.0
  :	:
  (36583, 4770)	1.0
  (36583, 4824)	1.0
  (36583, 4854)	1.0
  (36583, 4910)	1.0
  (36583, 4920)	1.0
  (36583, 4942)	1.0
  (36583, 4955)	1.0
  (36583, 5030)	1.0
  (36583, 5057)	1.0
  (36583, 5059)	1.0
  (36583, 5110)	1.0
  (36583, 5132)	1.0
  (36583, 5178)	1.0
  (36583, 5296)	1.0
  (36583, 5397)	1.0
  (36587, 3173)	1.0
  (36588, 4063)	1.0
  (36588, 5285)	1.0
  (36589, 962)	1.0
  (36589, 980)	1.0
  (36589, 1723)	1.0
  (36589, 3907)	1.0
  (36589, 4830)	1.0
  (36589, 4972)	1.0
  (36590, 2301)	1.0


In [16]:
tpm = np.load('/oak/stanford/groups/ljerby/SharedResources/Akana2024/Data/A375_tpm.npy')
tpm
# the large .npy file has been deleted manually

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
tpm = csr_array(tpm)
print(tpm)
sparse.save_npz('/oak/stanford/groups/ljerby/SharedResources/Akana2024/Data/A375_tpm',tpm)
# sparse format can be more efficient and compact for perturb-seq data
# read the data with:
# tpm = sparse.load_npz('path_to_your_file')
# convert to numpy:
# tpm = tpm.toarray()

  (0, 1011)	2.6348996598829344
  (0, 1649)	2.995917397372941
  (3, 684)	2.0935152393546157
  (3, 3503)	3.5431954604045344
  (3, 4658)	1.4147219856578566
  (3, 4712)	4.205229657505018
  (3, 4783)	1.1354143456439154
  (6, 50)	2.9739472350388185
  (6, 314)	2.3590103963767923
  (6, 550)	2.2522369740695347
  (6, 985)	1.7849746629094176
  (6, 1072)	2.448403056228697
  (6, 1268)	2.2468461139169853
  (6, 1697)	3.077324394460756
  (6, 2511)	2.610954857437144
  (6, 3279)	2.9034512884495185
  (6, 3587)	1.2664204171575502
  (6, 3604)	2.822723024979745
  (6, 3835)	1.2294147997947165
  (6, 3880)	1.299285572835204
  (6, 3910)	1.5745545027405572
  (6, 3924)	1.3575245148371655
  (6, 4225)	1.2628879903327286
  (6, 4246)	1.27321304112732
  (6, 4352)	2.0421427924122666
  :	:
  (36583, 4770)	1.5693406518703807
  (36583, 4824)	5.244139989647901
  (36583, 4854)	1.3592173613123864
  (36583, 4910)	3.4527613034997313
  (36583, 4920)	6.528636965521695
  (36583, 4942)	1.5653052964302312
  (36583, 4955)	1.48612090

In [20]:
targets = np.load('/oak/stanford/groups/ljerby/SharedResources/Akana2024/Data/A375_targets.npy',allow_pickle=True)
print(targets)
labels = pd.read_excel('/oak/stanford/groups/ljerby/SharedResources/Akana2024/Data/CRISPRa_Screen_TCRvsWT_04_26_2023.xlsx')
print(labels)

[['HOXD13']
 ['PTMA']
 ['CASP8']
 ...
 ['MCL1']
 ['CCR1']
 ['NTC']]
         id  num     neg.score  neg.p.value   neg.fdr  neg.rank  \
0     STAG2  180  1.135900e-02     0.014511  0.083081       512   
1     MYBL1   84  1.441600e-01     0.245300  0.517817      1387   
2      PAX2   90  9.623500e-01     0.993250  1.000000      2877   
3      JUNB   81  7.315200e-03     0.009347  0.061193       449   
4      LIFR   86  9.186800e-02     0.168530  0.434843      1129   
...     ...  ...           ...          ...       ...       ...   
2914   RHOG   90  2.088400e-03     0.002311  0.022719       299   
2915  ITGAV   90  1.602200e-01     0.276870  0.558722      1450   
2916  WNT3A   90  1.206800e-12     0.000002  0.000056        20   
2917   CRKL   90  1.344300e-10     0.000002  0.000056        27   
2918    MYC   90  3.074400e-98     0.000002  0.000056         1   

      neg.goodsgrna  neg.lfc     pos.score  pos.p.value  pos.fdr  pos.rank  \
0                34  0.83269  7.557300e-20     0.

In [32]:
targets = targets.squeeze()
print(targets)
print(np.unique(targets))
sens = labels[labels['neg.p.value']<=0.05]['id'].tolist()
print(sorted(sens))
resis = labels[labels['pos.p.value']<=0.05]['id'].tolist()
print(sorted(resis))

['HOXD13' 'PTMA' 'CASP8' ... 'MCL1' 'CCR1' 'NTC']
['APP' 'B2M' 'BAK1' 'BCL2A1' 'BCL2L1' 'BID' 'BTG2' 'CASP8' 'CCL22' 'CCNE2'
 'CCR1' 'CD274' 'CD40' 'CD40LG' 'CD44' 'CIC' 'COL1A1' 'CTAG1A' 'CTNND2'
 'DLL1' 'DLL4' 'DUSP9' 'E2F1' 'ETV6' 'FAS' 'FOSB' 'GAS6' 'GSPT2' 'HGF'
 'HNF4A' 'HOXD13' 'IFNB1' 'IL15' 'IRF1' 'IRS4' 'JUN' 'JUNB' 'KIAA0368'
 'KLF4' 'LIFR' 'MCL1' 'MLLT3' 'MYC' 'NCAM1' 'NIPBL' 'NTC' 'PAX2' 'PDPN'
 'PRDM16' 'PTMA' 'SAFB' 'STAG2' 'TBX5' 'TCF7L2' 'TNC' 'TP73' 'TRPS1'
 'TSPYL2' 'VIM' 'WNT1' 'WNT3' 'WNT3A']
['A4GALT', 'ABCA13', 'ABCA4', 'ABCA5', 'ACADM', 'ACSL6', 'ACTL6B', 'ACTR3', 'ACYP1', 'ADAMTS12', 'ADAMTSL5', 'ADCY3', 'ADCY5', 'ADCY6', 'ADCY9', 'ADM2', 'AFAP1L2', 'AFF4', 'AHR', 'AICDA', 'AIM1', 'AKAP2', 'AKR1C2', 'AKR1D1', 'ALCAM', 'ALDH2', 'ALDH7A1', 'ALS2', 'AMD1', 'AMPD1', 'ANAPC4', 'ANP32B', 'APBB2', 'APC', 'APC2', 'APLF', 'APOBEC3A', 'APP', 'ARGLU1', 'ARHGEF12', 'ARHGEF7', 'ARID1A', 'ARL2BP', 'ATG4A', 'ATP13A1', 'ATP6V1G3', 'ATRX', 'BAK1', 'BCAR1', 'BCAS3', 'BCAT1', 'BC

In [46]:
hold_in = []
hold_out = []
for gene in np.unique(targets):
    idx = labels['id']==gene
    if len(labels[idx]) > 0: 
        print(labels[idx]['id'].to_numpy(), labels[idx]['neg.p.value'].to_numpy(), labels[idx]['pos.p.value'].to_numpy())
        if np.random.rand() >= 0.05:
            hold_in.append(gene)
        else:
            hold_out.append(gene)
    else:
        print(gene)
        hold_out.append(gene)

['APP'] [6.612e-05] [0.96325]
B2M
['BAK1'] [1.6954e-06] [0.93994]
['BCL2A1'] [0.99968] [1.6954e-06]
['BCL2L1'] [0.99655] [0.047869]
['BID'] [1.6954e-06] [0.62507]
['BTG2'] [0.45342] [1.6954e-06]
['CASP8'] [1.6954e-06] [0.92587]
['CCL22'] [1.6954e-06] [0.77728]
['CCNE2'] [1.6954e-06] [0.1734]
['CCR1'] [0.001219] [0.4403]
CD274
['CD40'] [0.0094992] [0.0050471]
['CD40LG'] [0.24535] [0.57468]
['CD44'] [0.99999] [1.6954e-06]
['CIC'] [5.0861e-06] [0.96928]
['COL1A1'] [0.39432] [1.6954e-06]
['CTAG1A'] [1.6954e-06] [0.49514]
['CTNND2'] [4.9166e-05] [0.080434]
['DLL1'] [0.0062508] [0.28937]
['DLL4'] [1.6954e-06] [0.53397]
['DUSP9'] [0.0012359] [1.6954e-06]
['E2F1'] [0.065036] [0.0003679]
['ETV6'] [0.83948] [1.6954e-06]
['FAS'] [1.6954e-06] [0.9733]
['FOSB'] [0.027731] [1.6954e-06]
['GAS6'] [0.079827] [0.64897]
['GSPT2'] [0.73442] [1.6954e-06]
['HGF'] [0.10687] [1.6954e-06]
['HNF4A'] [0.55564] [1.6954e-06]
['HOXD13'] [0.24993] [1.6954e-06]
['IFNB1'] [1.6954e-06] [0.66442]
['IL15'] [8.4769e-06] [

In [47]:
print(hold_in)
print(hold_out)

['APP', 'BAK1', 'BCL2A1', 'BCL2L1', 'BID', 'BTG2', 'CASP8', 'CCL22', 'CCNE2', 'CCR1', 'CD40', 'CD40LG', 'CD44', 'CIC', 'COL1A1', 'CTAG1A', 'CTNND2', 'DLL1', 'DLL4', 'DUSP9', 'E2F1', 'ETV6', 'FAS', 'FOSB', 'GAS6', 'GSPT2', 'HGF', 'HNF4A', 'HOXD13', 'IFNB1', 'IL15', 'IRF1', 'IRS4', 'JUN', 'JUNB', 'KIAA0368', 'LIFR', 'MCL1', 'MLLT3', 'MYC', 'NCAM1', 'NIPBL', 'PAX2', 'PDPN', 'PRDM16', 'PTMA', 'SAFB', 'STAG2', 'TBX5', 'TCF7L2', 'TNC', 'TP73', 'TSPYL2', 'VIM', 'WNT1', 'WNT3', 'WNT3A']
['B2M', 'CD274', 'KLF4', 'NTC', 'TRPS1']


In [60]:
te_ids = []
tr_ids = []
for i in range(len(targets)):
    gene = targets[i]
    if gene in hold_out:
        te_ids.append(i)
    elif gene in hold_in:
        if np.random.rand() >= 0.1:
            tr_ids.append(i)
        else:
            te_ids.append(i)
            te_ids_in.append(i)
print(len(tr_ids))
print(len(te_ids))
print(len(targets))

3866
1582
5448


In [62]:
pvalue_dict = {}
for gene in np.unique(targets):
    idx = labels['id']==gene
    if len(labels[idx]) > 0: 
        print(labels[idx]['id'].to_numpy(), labels[idx]['neg.p.value'].to_numpy(), labels[idx]['pos.p.value'].to_numpy())
        pvalue_dict[gene] = [labels[idx]['neg.p.value'].to_numpy()[0], labels[idx]['pos.p.value'].to_numpy()[0]]
print(pvalue_dict)

['APP'] [6.612e-05] [0.96325]
['BAK1'] [1.6954e-06] [0.93994]
['BCL2A1'] [0.99968] [1.6954e-06]
['BCL2L1'] [0.99655] [0.047869]
['BID'] [1.6954e-06] [0.62507]
['BTG2'] [0.45342] [1.6954e-06]
['CASP8'] [1.6954e-06] [0.92587]
['CCL22'] [1.6954e-06] [0.77728]
['CCNE2'] [1.6954e-06] [0.1734]
['CCR1'] [0.001219] [0.4403]
['CD40'] [0.0094992] [0.0050471]
['CD40LG'] [0.24535] [0.57468]
['CD44'] [0.99999] [1.6954e-06]
['CIC'] [5.0861e-06] [0.96928]
['COL1A1'] [0.39432] [1.6954e-06]
['CTAG1A'] [1.6954e-06] [0.49514]
['CTNND2'] [4.9166e-05] [0.080434]
['DLL1'] [0.0062508] [0.28937]
['DLL4'] [1.6954e-06] [0.53397]
['DUSP9'] [0.0012359] [1.6954e-06]
['E2F1'] [0.065036] [0.0003679]
['ETV6'] [0.83948] [1.6954e-06]
['FAS'] [1.6954e-06] [0.9733]
['FOSB'] [0.027731] [1.6954e-06]
['GAS6'] [0.079827] [0.64897]
['GSPT2'] [0.73442] [1.6954e-06]
['HGF'] [0.10687] [1.6954e-06]
['HNF4A'] [0.55564] [1.6954e-06]
['HOXD13'] [0.24993] [1.6954e-06]
['IFNB1'] [1.6954e-06] [0.66442]
['IL15'] [8.4769e-06] [0.69043]
[

In [64]:
Y = []
empty_pvalues = np.array([[-1,-1]])
for gene in targets:
    if pvalue_dict.get(gene) is None:
        Y.append(empty_pvalues)
    else:
        Y.append(np.expand_dims(pvalue_dict[gene], axis=0))
Y = np.concatenate(Y, axis=0)
print(Y)
print(Y.shape)

[[ 2.4993e-01  1.6954e-06]
 [ 1.6954e-06  6.7351e-01]
 [ 1.6954e-06  9.2587e-01]
 ...
 [ 8.9006e-01  1.6954e-06]
 [ 1.2190e-03  4.4030e-01]
 [-1.0000e+00 -1.0000e+00]]
(5448, 2)


In [66]:
np.savez('/oak/stanford/groups/ljerby/SharedResources/Akana2024/Data/A375_labels_and_extras', Y=Y, pvalue_dict=pvalue_dict, tr_ids=tr_ids, te_ids=te_ids, hold_in=hold_in, hold_out=hold_out)

In [71]:
np.where(Y[:,0]==-1)[0].shape

(936,)

In [72]:
ct = 0
for gene in targets:
    if gene in ['B2M', 'CD274', 'NTC']:
        ct += 1
print(ct)

# only a small verification

936


In [75]:
conditions = np.load('/oak/stanford/groups/ljerby/SharedResources/Akana2024/Data/A375_condition.npy')
conditions

array(['Monoculture', 'Monoculture', 'Monoculture', ..., 'Coculture',
       'Coculture', 'Coculture'], dtype='<U11')

In [77]:
conditions = (conditions == 'Coculture').astype(float)
conditions

array([0., 0., 0., ..., 1., 1., 1.])

In [81]:
print(tpm.shape)
print(cd.shape)
conditions = sparse.csr_matrix(conditions)
tpm = sparse.vstack([conditions, tpm])
cd = sparse.vstack([conditions, cd])
print(tpm.shape)
print(cd.shape)

(36591, 5448)
(36591, 5448)
(36592, 5448)
(36592, 5448)


In [82]:
tpm = tpm.transpose()
cd = cd.transpose()
print(tpm.shape)
print(cd.shape)

(5448, 36592)
(5448, 36592)


In [89]:
sparse.save_npz('/oak/stanford/groups/ljerby/SharedResources/Akana2024/Data/A375_cd',cd)
sparse.save_npz('/oak/stanford/groups/ljerby/SharedResources/Akana2024/Data/A375_tpm',tpm)